//! Build-time code generation for metric natural-language prose.
//!
//! The ontology metric dictionary (`ontology/schema/metric_dictionary.yaml`) is
//! the single source of truth for metric identities, display names, and filing
//! descriptions. This build script reads that file and emits a Rust match arm
//! for each canonical metric so the planner can convert a machine identifier
//! like `gross_margin` into the filing-language phrase `gross margin` without a
//! hand-maintained parallel mapping.
//!
//! The checked-in runtime schema snapshot is the only build input. A release
//! build must be reproducible from this repository and must fail if that
//! snapshot is absent or invalid.

use std::env;
use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct MetricDictionary {
    canonical_metrics: std::collections::BTreeMap<String, MetricEntry>,
}

#[derive(Debug, Deserialize)]
struct MetricEntry {
    display_name: String,
    #[serde(default)]
    #[allow(dead_code)]
    description: String,
    #[serde(default)]
    aliases: Vec<String>,
}

fn main() {
    let yaml = metric_dictionary_path();
    println!("cargo:rerun-if-changed={}", yaml.display());

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    let dest = out_dir.join("metric_prose.rs");

    let text = fs::read_to_string(&yaml).unwrap_or_else(|err| {
        panic!(
            "sealed metric_dictionary.yaml at {} could not be read: {err}",
            yaml.display()
        )
    });
    let dict = serde_yaml_ng::from_str::<MetricDictionary>(&text).unwrap_or_else(|err| {
        panic!(
            "sealed metric_dictionary.yaml at {} failed to parse: {err}",
            yaml.display()
        )
    });
    assert!(
        !dict.canonical_metrics.is_empty(),
        "sealed metric_dictionary.yaml must contain canonical metrics"
    );
    let source = generate_module(&dict);

    if let Err(err) = fs::write(&dest, source) {
        panic!("failed to write {}: {err}", dest.display());
    }
}

fn metric_dictionary_path() -> PathBuf {
    PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by Cargo"))
        .join("../../services/krw-ontology-runtime/src/krw_capability_runtime/resources/ontology/schema/metric_dictionary.yaml")
}

/// Build the prose phrase used for retrieval. We prefer the description (which
/// contains filing vocabulary like "net sales"), falling back to the display
/// name lower-cased. Aliases that contain filing vocabulary are appended so a
/// metric like `revenue` also matches the common `net sales` filing phrase.
fn prose_for(entry: &MetricEntry) -> String {
    let display_lower = entry.display_name.to_lowercase();
    let mut parts: Vec<String> = vec![display_lower.clone()];
    for alias in &entry.aliases {
        let lower = alias.to_lowercase();
        // Keep only alias phrases that add filing vocabulary the display name
        // does not already cover (for example `net_sales` for `revenue`).
        if !display_lower
            .split_whitespace()
            .any(|word| lower.contains(word))
        {
            parts.push(lower);
        }
    }
    parts.join(" ")
}

fn generate_module(dict: &MetricDictionary) -> String {
    #![allow(clippy::format_push_string)]
    let mut arms = String::new();
    for (identifier, entry) in &dict.canonical_metrics {
        let prose = prose_for(entry);
        let prose_literal = rust_str_literal(&prose);
        arms.push_str(&format!("        {identifier:?} => {prose_literal},\n"));
    }
    format!(
        "// Auto-generated by build.rs from ontology metric_dictionary.yaml.\n\
         // Do not edit by hand; re-run the build to regenerate.\n\
         /// Map a canonical metric identifier to the natural filing-language\n\
         /// phrase used for ontology retrieval. Generated from the ontology\n\
         /// metric dictionary at build time, so adding a metric to the\n\
         /// dictionary automatically updates this mapping.\n\
         pub(crate) fn metric_as_prose(metric: &str) -> &'static str {{\n\
         \x20   match metric {{\n\
         {arms}\
         \x20       _ => \"\",\n\
         \x20   }}\n\
         }}\n"
    )
}

/// Produce a Rust string literal with proper escaping for the prose phrase.
fn rust_str_literal(value: &str) -> String {
    let mut out = String::from("\"");
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
