//! Build-time code generation for ontology-derived contract constants.
//!
//! The ontology metric dictionary is the single source of truth for canonical
//! metric identities. This script reads it and emits a `const` slice so the
//! contract validator and the planner share one authoritative list instead of
//! a hand-maintained parallel copy.
//!
//! When `KRW_ONTOLOGY_ROOT` is unset the build still succeeds with an empty
//! fallback so the crate compiles in environments without the ontology (for
//! example `cargo doc`). Production and test builds always set it.

use std::env;
use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct MetricDictionary {
    canonical_metrics: std::collections::BTreeMap<String, serde_yaml_ng::Value>,
}

fn main() {
    println!("cargo:rerun-if-env-changed=KRW_ONTOLOGY_ROOT");
    if let Ok(root) = env::var("KRW_ONTOLOGY_ROOT") {
        let yaml = PathBuf::from(root).join("ontology/schema/metric_dictionary.yaml");
        if yaml.exists() {
            println!("cargo:rerun-if-changed={}", yaml.display());
        }
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    let dest = out_dir.join("ontology_metrics.rs");

    let source = match metric_dictionary_path() {
        Some(path) => match fs::read_to_string(&path) {
            Ok(text) => match serde_yaml_ng::from_str::<MetricDictionary>(&text) {
                Ok(dict) => generate_metrics_const(&dict),
                Err(err) => {
                    panic!(
                        "metric_dictionary.yaml at {} failed to parse: {err}",
                        path.display()
                    );
                }
            },
            Err(err) => {
                panic!(
                    "metric_dictionary.yaml at {} could not be read: {err}",
                    path.display()
                );
            }
        },
        None => String::from(
            "// KRW_ONTOLOGY_ROOT not set; emitting empty metric list.\n\
             pub(crate) const RESEARCH_PROPOSAL_V4_METRICS: &[&str] = &[];\n",
        ),
    };

    if let Err(err) = fs::write(&dest, source) {
        panic!("failed to write {}: {err}", dest.display());
    }
}

fn metric_dictionary_path() -> Option<PathBuf> {
    let root = env::var("KRW_ONTOLOGY_ROOT")
        .ok()
        .filter(|r| !r.is_empty())?;
    let path = PathBuf::from(root).join("ontology/schema/metric_dictionary.yaml");
    path.exists().then_some(path)
}

fn generate_metrics_const(dict: &MetricDictionary) -> String {
    #![allow(clippy::format_push_string)]
    let mut entries: Vec<&str> = dict.canonical_metrics.keys().map(String::as_str).collect();
    entries.sort_unstable();
    let mut out = String::from(
        "// Auto-generated by build.rs from ontology metric_dictionary.yaml.\n\
         /// Canonical metric identifiers accepted by `ResearchProposal` v4. Generated\n\
         /// from the ontology metric dictionary at build time so adding a metric to\n\
         /// the dictionary automatically updates validation.\n\
         pub(crate) const RESEARCH_PROPOSAL_V4_METRICS: &[&str] = &[\n",
    );
    for entry in entries {
        out.push_str(&format!("    {entry:?},\n"));
    }
    out.push_str("];\n");
    out
}
