[package]
name = "krw-agent-deploy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
krw-agent-protocol = { path = "../../crates/protocol" }
krw-agent-release-authorization = { path = "../../crates/release-authorization" }
serde.workspace = true
serde_jcs.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
